## **📁 Data Overview (Giới thiệu dữ liệu)**

Bộ dữ liệu **Student Alcohol Consumption** chia thành 2 bộ dữ liệu nhỏ:
* **student_mat.csv**: file chứa đặc trưng của học sinh tương ứng với số điểm Toán
  * Gồm có  ~**395** dòng và **33** cột
* **student_por.csv**: file chứa đặc trưng của học sinh tương ứng với số điểm Tiếng Bồ
  * Gồm có ~**649** dòng và **33** cột

**Nguồn**: [Kaggle](https://www.kaggle.com/datasets/uciml/student-alcohol-consumption?select=student-mat.csv)

Bộ dữ liệu đươc thu thập ở 2 trường cấp 2 với điểm số của hai bộ môn Toán và Tiếng Bồ. Bao gồm các đặc trưng về mạng xã hội, thông tin học tập, giới tính của học sinh, ...  

Mục tiêu của bộ dữ liệu này được sử dụng nhằm dự đoán số điểm của các học sinh đồng thời đánh giá xem yếu tố nào ảnh hưởng đến điểm số của học sinh


## **🧩 Data Structure (Cấu trúc dữ liệu)**

### **Đặc trưng của các cột bao gồm**

* **Thông tin cá nhân**
  * `sex`: Giới tính (F - Nữ, M - Nam) - Cate
  * `age`: Tuổi - Num
  * `address`: Địa chỉ (U - Urban, R - Rural) - Cate
  * `famsize`: Số lượng người trong gia đình (LE3 - Dưới hoặc bảng 3, GE3 - Lớn hơn 3) - Cate
  * `Pstatus`: Xa nhà hay thành phố (T - Sống cùng, A - Riêng) - Catr
  * `Medu`: Trình độ mẹ (0 - không, 1 - cáp 1, 2 - cấp 2, 3 - cấp 3, 4 - cao học ) - Num
  * `Fedu`: Trình độ cha (0 - không, 1 - cáp 1, 2 - cấp 2, 3 - cấp 3, 4 - cao học ) - Num
  * `Mjob`: Công việc mẹ - Cate
  * `Fjob`: Công việc cha - Cate
* **Thông tin học tập**
  * `school`: Trường theo học (GP - Gabriel Pereira, MS -  Mousinho da Silveira ) - Cate
  * `reason`: Lý do lựa chọn trường - Cate
  * `guardian`: Người giám hộ - Cate
* **Thông tin thời gian**
  * `traveltime`: Thời gian nhà đến trường - Num  
  * `studytime`: Thời gian học - Num
  * `failures`: Số lượng lớp rớt - Num
* **Thông tin khác**
  * `schoolsup`: Hỗ trợ nhà trường (Y - Có, K - Không) - Cate
  * `famsup`: Hỗ trợ gia đình (Y - Có, K - Không) - Cate
  * `paid`: Trả thêm cho học bổ trợ (Y - Có, K - Không) - Cate
* **Thông tin sinh hoạt**
  * `activities`: Tham gia ngoại khóa (Y - Có, K - Không) - Cate
  * `nursery`: Đã học mẫu gíao (Y - Có, K - Không) - Cate
  * `higher`: Muốn học cao học (Y - Có, K - Không) - Cate
  * `internet`: Được truy cập mạng ở nhà (Y - Có, K - Không) - Cate
  * `romantic`: Có hẹn hò (Y - Có, K - Không) - Cate
* **Thông tin sức khỏe tinh thần**
  * `famrel`: Chất lượng mỗi quan hệ (từ 1 đến 5) - Num
  * `freetime`: Thời gian rảnh sau học (từ 1 đến 5) - Num
  * `goout`: Đi chơi với bạn (từ 1 đến 5) - Num
  * `Dalc`: Sức khỏe tin thần trong ngày (từ 1 đến 5) - Num
  * `Walc`: Sức khỏe tinh thần cuối tuần (từ 1 đến 5) - Num
  * `health`: Sức khỏe cá nhân (từ 1 đến 5) - Num
  * `absences`: Số buổi vắng học (từ 0 đến 93) - Num
* **Thông tin điểm số**
  * `G1`: Điểm bài thi thứ 1 (từ 1 đến 20) - Num
  * `G2`: Điểm bài thi thứ 2 (từ 1 đến 20) - Num
  * `G3`: Điểm bài thi thứ 3 **(target)** (từ 1 đến 20) - Num

In [18]:
student_mat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64 
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64 
 7   Fedu        395 non-null    int64 
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64 
 13  studytime   395 non-null    int64 
 14  failures    395 non-null    int64 
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher    

In [19]:
student_por.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64 
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64 
 7   Fedu        649 non-null    int64 
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64 
 13  studytime   649 non-null    int64 
 14  failures    649 non-null    int64 
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher    

## **🔍 Data Preview (Xem trước dữ liệu)**

Xuất 5 dòng đầu của mỗi bộ dữ liệu

In [1]:
import pandas as pd
import numpy as np

In [2]:
student_mat = pd.read_csv('student-mat.csv')
student_por = pd.read_csv('student-por.csv')

In [4]:
student_mat.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [5]:
student_por.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

## **📊 Descriptive Statistics (Thống kê mô tả)**

In [6]:
student_mat.describe().T

count       mean       std   min   25%   50%   75%   max
age         395.0  16.696203  1.276043  15.0  16.0  17.0  18.0  22.0
Medu        395.0   2.749367  1.094735   0.0   2.0   3.0   4.0   4.0
Fedu        395.0   2.521519  1.088201   0.0   2.0   2.0   3.0   4.0
traveltime  395.0   1.448101  0.697505   1.0   1.0   1.0   2.0   4.0
studytime   395.0   2.035443  0.839240   1.0   1.0   2.0   2.0   4.0
failures    395.0   0.334177  0.743651   0.0   0.0   0.0   0.0   3.0
famrel      395.0   3.944304  0.896659   1.0   4.0   4.0   5.0   5.0
freetime    395.0   3.235443  0.998862   1.0   3.0   3.0   4.0   5.0
goout       395.0   3.108861  1.113278   1.0   2.0   3.0   4.0   5.0
Dalc        395.0   1.481013  0.890741   1.0   1.0   1.0   2.0   5.0
Walc        395.0   2.291139  1.287897   1.0   1.0   2.0   3.0   5.0
health      395.0   3.554430  1.390303   1.0   3.0   4.0   5.0   5.0
absences    395.0   5.708861  8.003096   0.0   0.0   4.0   8.0  75.0
G1          395.0  10.908861  3.319195   3.0   8.0  11.0  13.0  19.0
G2          395.0  10.713924  3.761505   0.0   9.0  11.0  13.0  19.0
G3          395.0  10.415190  4.581443   0.0   8.0  11.0  14.0  20.0

In [9]:
student_mat.describe(include='object').T

count unique     top freq
school       395      2      GP  349
sex          395      2       F  208
address      395      2       U  307
famsize      395      2     GT3  281
Pstatus      395      2       T  354
Mjob         395      5   other  141
Fjob         395      5   other  217
reason       395      4  course  145
guardian     395      3  mother  273
schoolsup    395      2      no  344
famsup       395      2     yes  242
paid         395      2      no  214
activities   395      2     yes  201
nursery      395      2     yes  314
higher       395      2     yes  375
internet     395      2     yes  329
romantic     395      2      no  263

In [7]:
student_por.describe().T

count       mean       std   min   25%   50%   75%   max
age         649.0  16.744222  1.218138  15.0  16.0  17.0  18.0  22.0
Medu        649.0   2.514638  1.134552   0.0   2.0   2.0   4.0   4.0
Fedu        649.0   2.306626  1.099931   0.0   1.0   2.0   3.0   4.0
traveltime  649.0   1.568567  0.748660   1.0   1.0   1.0   2.0   4.0
studytime   649.0   1.930663  0.829510   1.0   1.0   2.0   2.0   4.0
failures    649.0   0.221880  0.593235   0.0   0.0   0.0   0.0   3.0
famrel      649.0   3.930663  0.955717   1.0   4.0   4.0   5.0   5.0
freetime    649.0   3.180277  1.051093   1.0   3.0   3.0   4.0   5.0
goout       649.0   3.184900  1.175766   1.0   2.0   3.0   4.0   5.0
Dalc        649.0   1.502311  0.924834   1.0   1.0   1.0   2.0   5.0
Walc        649.0   2.280431  1.284380   1.0   1.0   2.0   3.0   5.0
health      649.0   3.536210  1.446259   1.0   2.0   4.0   5.0   5.0
absences    649.0   3.659476  4.640759   0.0   0.0   2.0   6.0  32.0
G1          649.0  11.399076  2.745265   0.0  10.0  11.0  13.0  19.0
G2          649.0  11.570108  2.913639   0.0  10.0  11.0  13.0  19.0
G3          649.0  11.906009  3.230656   0.0  10.0  12.0  14.0  19.0

In [10]:
student_por.describe(include='object').T

count unique     top freq
school       649      2      GP  423
sex          649      2       F  383
address      649      2       U  452
famsize      649      2     GT3  457
Pstatus      649      2       T  569
Mjob         649      5   other  258
Fjob         649      5   other  367
reason       649      4  course  285
guardian     649      3  mother  455
schoolsup    649      2      no  581
famsup       649      2     yes  398
paid         649      2      no  610
activities   649      2      no  334
nursery      649      2     yes  521
higher       649      2     yes  580
internet     649      2     yes  498
romantic     649      2      no  410

Gồm 395 đối với **Toán** và 649 mẫu đối với **Tiếng Bồ** thuộc trong độ tuổi cấp 2 - 16 tuổi đến 22 tuổi, đáng lưu ý như điểm Toán của cả ba bài kiểm tra ở một Tiếng Bồ cao hơn điểm Toán. Độ lệch cũng khác nhau khi điểm Toán giao động trong khoảng 8.0 (25%) còn tiếng Bồ là 10.0 (25%) tất cả đều được đo trên thang điểm 20. Sức khỏe cũng đạt mức bình tường và không có gì đáng nói.

Phân bố các đặc trưng phân loại của cả hai bộ dữ liệu giống nhau nên cũng không có gì đáng nói

## **❗ Missing Values (Dữ liệu thiếu)**

In [11]:
student_mat.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [16]:
student_mat.duplicated().sum()

np.int64(0)

In [12]:
student_por.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [17]:
student_por.duplicated().sum()

np.int64(0)

Trong 2 bộ dữ liệu không có cột nào bị thiếu

## **✨Initial Insights (Nhận xét ban đầu)**


* Bộ dữ liệu điểm Tiếng Bồ nhiều hơn hẳn so với bộ dữ liệu điểm Toán
* Trong cột không có dữ liệu bị thiếu và bị trùng
* Không thể gộp bảng dữ liệu Bồ và Toán lại được với nhau do không có điểm chung và ta chỉ biết dữ liệu dược thu thâp từ 2 trường. Do đó không có đủ dữ kiện để gộp
* Có thể dự đoán điểm số và phân cụm học sinh
* Có một số học sinh thuộc trong cả 2 bộ dữ liệu do đó ta sẽ sử dụng riêng lẻ hai bộ dữ liệu để phân tích chuyên sâu và gộp chúng lại khi huấn luyên mô hình